mv 113_Phalaenopsis_aphrodite_genomic.fa.mod.pass.list 113_Phalaenopsis_aphrodite.fa.pass.list
mv 123_Raddia_distichophylla_genomic.fa.mod.pass.list 123_Raddia_distichophylla.fa.pass.list
mv 132_Oryza_punctata_genomic.fa.mod.pass.list 132_Oryza_punctata.fa.pass.list
mv 137_Brachypodium_distachyon_genomic.fa.mod.pass.list 137_Brachypodium_distachyon.fa.pass.list
mv 139_Lolium_perenne_genomic.fa.mod.pass.list 139_Lolium_perenne.fa.pass.list
mv 13_Cymbomonas_tetramitiformis_genomic.fa.mod.pass.list 13_Cymbomonas_tetramitiformis.fa.pass.list
mv 140_Hordeum_bulbosum_genomic.fa.mod.pass.list 140_Hordeum_bulbosum.fa.pass.list
mv 143_Secale_cereale_genomic.fa.mod.pass.list 143_Secale_cereale.fa.pass.list
mv 144_Aegilops_tauschii_genomic.fa.mod.pass.list 144_Aegilops_tauschii.fa.pass.list
mv 149_Eleusine_indica_genomic.fa.mod.pass.list 149_Eleusine_indica.fa.pass.list
mv 150_Oropetium_thomaeum_genomic.fa.mod.pass.list 150_Oropetium_thomaeum.fa.pass.list
mv 152_Eragrostis_tef_genomic.fa.mod.pass.list 152_Eragrostis_tef.fa.pass.list
mv 154_Zoysia_japonica_genomic.fa.mod.pass.list 154_Zoysia_japonica.fa.pass.list
mv 156_Zoysia_pacifica_genomic.fa.mod.pass.list 156_Zoysia_pacifica.fa.pass.list
mv 159_Saccharum_hybrid_cultivar_genomic.fa.mod.pass.list 159_Saccharum_hybrid_cultivar.fa.pass.list
mv 160_Saccharum_spontaneum_genomic.fa.mod.pass.list 160_Saccharum_spontaneum.fa.pass.list
mv 161_Sorghum_bicolor_genomic.fa.mod.pass.list 161_Sorghum_bicolor.fa.pass.list
mv 164_Echinochloa_crus-galli_genomic.fa.mod.pass.list 164_Echinochloa_crus-galli.fa.pass.list
mv 169_Urochloa_ruziziensis_genomic.fa.mod.pass.list 169_Urochloa_ruziziensis.fa.pass.list
mv 171_Panicum_hallii_genomic.fa.mod.pass.list 171_Panicum_hallii.fa.pass.list
mv 172_Eichhornia_paniculata_genomic.fa.mod.pass.list 172_Eichhornia_paniculata.fa.pass.list
mv 175_Musa_balbisiana_genomic.fa.mod.pass.list 175_Musa_balbisiana.fa.pass.list
mv 176_Musa_itinerans_genomic.fa.mod.pass.list 176_Musa_itinerans.fa.pass.list
mv 179_Eschscholzia_californica_genomic.fa.mod.pass.list 179_Eschscholzia_californica.fa.pass.list
mv 182_Aquilegia_coerulea_genomic.fa.mod.pass.list 182_Aquilegia_coerulea.fa.pass.list
mv 225_Cicer_arietinum_genomic.fa.mod.pass.list 225_Cicer_arietinum.fa.pass.list
mv 22_Eudorina_genomic.fa.mod.pass.list 22_Eudorina.fa.pass.list
mv 239_Mucuna_pruriens_genomic.fa.mod.pass.list 239_Mucuna_pruriens.fa.pass.list
mv 279_Rosa_multiflora_genomic.fa.mod.pass.list 279_Rosa_multiflora.fa.pass.list
mv 28_Haematococcus_pluvialis_genomic.fa.mod.pass.list 28_Haematococcus_pluvialis.fa.pass.list
mv 297_Casuarina_equisetifolia_genomic.fa.mod.pass.list 297_Casuarina_equisetifolia.fa.pass.list
mv 298_Casuarina_glauca_genomic.fa.mod.pass.list 298_Casuarina_glauca.fa.pass.list
mv 2_Chondrus_crispus_genomic.fa.mod.pass.list 2_Chondrus_crispus.fa.pass.list
mv 313_Morella_rubra_genomic.fa.mod.pass.list 313_Morella_rubra.fa.pass.list
mv 315_Eucalyptus_camaldulensis_genomic.fa.mod.pass.list 315_Eucalyptus_camaldulensis.fa.pass.list
mv 339_Citrus_x_paradisi_x_Citrus_trifoliata_genomic.fa.mod.pass.list 339_Citrus_x_paradisi_x_Citrus_trifoliata.fa.pass.list
mv 381_Camelina_sativa_genomic.fa.mod.pass.list 381_Camelina_sativa.fa.pass.list
mv 425_Pereskia_humboldtii_genomic.fa.mod.pass.list 425_Pereskia_humboldtii.fa.pass.list
mv 439_Actinidia_chinensis_genomic.fa.mod.pass.list 439_Actinidia_chinensis.fa.pass.list
mv 44_Tetraselmis_striata_genomic.fa.mod.pass.list 44_Tetraselmis_striata.fa.pass.list
mv 454_Pogostemon_cablin_genomic.fa.mod.pass.list 454_Pogostemon_cablin.fa.pass.list
mv 45_Picocystis_genomic.fa.mod.pass.list 45_Picocystis.fa.pass.list
mv 464_Fraxinus_excelsior_genomic.fa.mod.pass.list 464_Fraxinus_excelsior.fa.pass.list
mv 46_Ulva_mutabilis_genomic.fa.mod.pass.list 46_Ulva_mutabilis.fa.pass.list
mv 477_Ipomoea_triloba_genomic.fa.mod.pass.list 477_Ipomoea_triloba.fa.pass.list
mv 479_Nicotiana_glauca_genomic.fa.mod.pass.list 479_Nicotiana_glauca.fa.pass.list
mv 47_Ulva_prolifera_genomic.fa.mod.pass.list 47_Ulva_prolifera.fa.pass.list
mv 480_Nicotiana_knightiana_genomic.fa.mod.pass.list 480_Nicotiana_knightiana.fa.pass.list
mv 491_Capsicum_chinense_genomic.fa.mod.pass.list 491_Capsicum_chinense.fa.pass.list
mv 492_Jaltomata_sinuosa_genomic.fa.mod.pass.list 492_Jaltomata_sinuosa.fa.pass.list
mv 4_Edaphochlamys_debaryana_genomic.fa.mod.pass.list 4_Edaphochlamys_debaryana.fa.pass.list
mv 521_Codonopsis_pilosula_genomic.fa.mod.pass.list 521_Codonopsis_pilosula.fa.pass.list
mv 5_Bathycoccus_prasinos_genomic.fa.mod.pass.list 5_Bathycoccus_prasinos.fa.pass.list
mv 6_Ostreococcus_tauri_genomic.fa.mod.pass.list 6_Ostreococcus_tauri.fa.pass.list
mv 74_Klebsormidium_nitens_genomic.fa.mod.pass.list 74_Klebsormidium_nitens.fa.pass.list
mv 75_Chara_braunii_genomic.fa.mod.pass.list 75_Chara_braunii.fa.pass.list
mv 78_Physcomitrella_patens_genomic.fa.mod.pass.list 78_Physcomitrella_patens.fa.pass.list
mv 79_Pleurozium_schreberi_genomic.fa.mod.pass.list 79_Pleurozium_schreberi.fa.pass.list
mv 7_Ostreococcus_sp._lucimarinus_genomic.fa.mod.pass.list 7_Ostreococcus_sp._lucimarinus.fa.pass.list
mv 81_Marchantia_polymorpha_genomic.fa.mod.pass.list 81_Marchantia_polymorpha.fa.pass.list
mv 82_Selaginella_kraussiana_genomic.fa.mod.pass.list 82_Selaginella_kraussiana.fa.pass.list
mv 84_Selaginella_tamariscina_genomic.fa.mod.pass.list 84_Selaginella_tamariscina.fa.pass.list
mv 87_Salvinia_cucullata_genomic.fa.mod.pass.list 87_Salvinia_cucullata.fa.pass.list
mv 88_Ginkgo_biloba_genomic.fa.mod.pass.list 88_Ginkgo_biloba.fa.pass.list
mv 89_Gnetum_montanum_genomic.fa.mod.pass.list 89_Gnetum_montanum.fa.pass.list
mv 91_Picea_glauca_genomic.fa.mod.pass.list 91_Picea_glauca.fa.pass.list
mv 93_Pinus_lambertiana_genomic.fa.mod.pass.list 93_Pinus_lambertiana.fa.pass.list
mv 9_Micromonas_commoda_genomic.fa.mod.pass.list 9_Micromonas_commoda.fa.pass.list
